# -*- coding: utf-8 -*-
"""Visuals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11IF05zKZsvjGHQeOu3Rv6sUPfkvvFKla

<a href="https://colab.research.google.com/github/ll-cooool-j/DS-Assignment/blob/main/arima_forecasting_ver%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

# Confirmed, Death and Recovered (logarithm scale), grouped by country
import matplotlib as mpl
import seaborn as sns
from pandas import read_csv
from pandas import datetime
from matplotlib import pyplot as plt

def parser(x):
	return datetime.strptime('202'+x, '%Y-%m-%d')

fig = plt.figure(figsize=(30,16))
mpl.style.use('seaborn-white')
my_pallete = sns.set_palette(['#E85B80','#98C35A', '#FFAE6B', '#7FF9E3', '#D883FF', '#AB6E3B'])

 
global1 = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Visuals/Basic%20visuals/Datasets%20of%20each%20country%20and%20Global/Global%20(SPSS).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
global1 = global1.drop(columns=['Infected','CFR', 'Recovery_rate', 'Mortality_rate'])
 
brazil1 = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Visuals/Basic%20visuals/Datasets%20of%20each%20country%20and%20Global/Highest%20Number%20of%20Infections%20Country%20~%20Brazil%20(SPSS).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
brazil1 = brazil1.drop(columns=['Infected','CFR', 'Recovery_rate', 'Mortality_rate'])
 
us1 = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Visuals/Basic%20visuals/Datasets%20of%20each%20country%20and%20Global/Highest%20Number%20of%20Infections%20Country%20~%20United%20States%20(SPSS).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
us1 = us1.drop(columns=['Infected','CFR', 'Recovery_rate', 'Mortality_rate'])

india1 = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Visuals/Basic%20visuals/Datasets%20of%20each%20country%20and%20Global/Highest%20Number%20of%20Infections%20Country%20~%20India%20(SPSS).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
india1 = india1.drop(columns=['Infected','CFR', 'Recovery_rate', 'Mortality_rate']) 

japan1 = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Visuals/Basic%20visuals/Datasets%20of%20each%20country%20and%20Global/Asian%20Country%20~%20Japan%20(SPSS).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
japan1 = japan1.drop(columns=['Infected','CFR', 'Recovery_rate', 'Mortality_rate'])

korea1 = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Visuals/Basic%20visuals/Datasets%20of%20each%20country%20and%20Global/Asian%20Country%20~%20South%20Korea%20(SPSS).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
korea1 = korea1.drop(columns=['Infected','CFR', 'Recovery_rate', 'Mortality_rate'])

vietnam1 = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Visuals/Basic%20visuals/Datasets%20of%20each%20country%20and%20Global/Asian%20Country%20~%20Vietnam%20(SPSS).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
vietnam1 = vietnam1.drop(columns=['Infected','CFR', 'Recovery_rate', 'Mortality_rate'])

fig2 = plt.figure(figsize=(20,16))
fig2.suptitle('Confirmed, Death and Recovered of Countries', fontsize=16)

sub11 = fig2.add_subplot(331)
sub11.set_title('Brazil')
sub11.plot(brazil1)
plt.yscale("log")

sub22 = fig2.add_subplot(332)
sub22.set_title('United States')
sub22.plot(us1)
plt.yscale("log")

sub33 = fig2.add_subplot(333)
sub33.set_title('India')
sub33.plot(india1)
plt.yscale("log")

sub44 = fig2.add_subplot(334)
sub44.set_title('Japan')
sub44.plot(japan1)
plt.yscale("log")

sub55 = fig2.add_subplot(335)
sub55.set_title('Korea')
sub55.plot(korea1)
plt.yscale("log")

sub66 = fig2.add_subplot(336)
sub66.set_title('Vietnam')
sub66.plot(vietnam1)
plt.yscale("log")

# Commented out IPython magic to ensure Python compatibility.
# Histograms for distribution analysing
import matplotlib as mpl
import seaborn as sns
from pandas import read_csv
from pandas import datetime
from matplotlib import pyplot as plt
import numpy as np
# %matplotlib inline

def parser(x):
	return datetime.strptime('202'+x, '%Y-%m-%d')

mpl.style.use('seaborn-white')
my_pallete = sns.set_palette(['#E85B80','#98C35A', '#FFAE6B', '#7FF9E3', '#D883FF', '#AB6E3B'])

global1 = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Visuals/Basic%20visuals/Datasets%20of%20each%20country%20and%20Global/Global%20(SPSS).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
global1 = global1.drop(columns=['Infected','CFR', 'Recovery_rate', 'Mortality_rate'])

plt.rcParams.update({'figure.figsize':(21,6), 'figure.dpi':100})
global_dis = plt.figure()
global_dis.suptitle('Global histograms', fontsize=16)

subA = global_dis.add_subplot(131)
plt.hist(global1['Confirmed'], bins=50)
plt.gca().set(title='Confirmed Frequency Histogram', xlabel = 'Number of people', ylabel='Frequency');

subB = global_dis.add_subplot(132)
plt.hist(global1['Deaths'], bins=50)
plt.gca().set(title='Deaths Frequency Histogram', xlabel = 'Number of people', ylabel='Frequency');

subC = global_dis.add_subplot(133)
plt.hist(global1['Recovered'], bins=50)
plt.gca().set(title='Recovered Frequency Histogram', xlabel = 'Number of people', ylabel='Frequency');

# đây là plot dành cho phần 5 - ARIMA
import matplotlib as mpl
import seaborn as sns
from pandas import read_csv
from pandas import datetime
from matplotlib import pyplot as plt

mpl.style.use('seaborn-white')
sns.set_palette("pastel")
 
def parser(x):
	return datetime.strptime('202'+x, '%Y-%m-%d')
 
gl0bal = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Datasets/Global%2C%20only%20Date%20and%20Infected%2C%20CSV%20formatted.csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
brazil = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Datasets/Datasets%20for%20ARIMA%20(Only%20Date%20%2B%20Infected)/Brazil%20(Date%20%2B%20Infected).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
india = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Datasets/Datasets%20for%20ARIMA%20(Only%20Date%20%2B%20Infected)/India%20(Date%20%2B%20Infected).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
japan = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Datasets/Datasets%20for%20ARIMA%20(Only%20Date%20%2B%20Infected)/Japan%20(Date%20%2B%20Infected).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
us = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Datasets/Datasets%20for%20ARIMA%20(Only%20Date%20%2B%20Infected)/United%20States%20(Date%20%2B%20Infected).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
korea = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Datasets/Datasets%20for%20ARIMA%20(Only%20Date%20%2B%20Infected)/South%20Korea%20(Date%20%2B%20Infected).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)
vietnam = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Datasets/Datasets%20for%20ARIMA%20(Only%20Date%20%2B%20Infected)/Vietnam%20(Date%20%2B%20Infected).csv', header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)

fig = plt.figure(figsize=(30,16))

sub1 = fig.add_subplot(331)
sub1.set_title('Brazil')
sub1.plot(brazil)

sub2 = fig.add_subplot(332)
sub2.set_title('US')
sub2.plot(us, color = '#E85B80')

sub3 = fig.add_subplot(333)
sub3.set_title('India')
sub3.plot(india, color = '#C2DF81')

sub4 = fig.add_subplot(334)
sub4.set_title('Japan')
sub4.plot(japan, color = '#FB8BDF')

sub5 = fig.add_subplot(335)
sub5.set_title('Korea')
sub5.plot(korea, color = '#FFAE6B')

sub6 = fig.add_subplot(336)
sub6.set_title('Vietnam')
sub6.plot(vietnam, color ='#D883FF')

sub7 = fig.add_subplot(338)
sub7.set_title('Global')
sub7.plot(gl0bal, color = '#AB6E3B')