# -*- coding: utf-8 -*-
"""plot 1 đồ thị nhiều đường.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1piwMDOI7XzWULT3lg38zCg5Ux6q7qOdK
"""

import numpy as np
import matplotlib as mpl
import seaborn as sns
from pandas import read_csv
from pandas import datetime
from matplotlib import pyplot as plt

mpl.style.use('seaborn-white')
my_pallete = sns.set_palette(['#E85B80', '#98C35A', '#FFAE6B', '#7FF9E3', '#D883FF', '#AB6E3B'])

fig= plt.figure(figsize=(10,6))
ax = fig.add_axes([0,0,1,1])
country = ['Brazil', 'US', 'India', 'Japan', 'Korea','Vietnam']
population = [212559409,331002647,1380004385,126476458,51269183,97338583]
ax.bar(country,population,color='#FFAE6B')
plt.show()