# -*- coding: utf-8 -*-
"""plot 1 đồ thị nhiều đường.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1piwMDOI7XzWULT3lg38zCg5Ux6q7qOdK
"""

import numpy as np
import matplotlib as mpl
import seaborn as sns
from pandas import read_csv
from pandas import datetime
from matplotlib import pyplot as plt

mpl.style.use('seaborn-white')
my_pallete = sns.set_palette(
    ['#E85B80', '#98C35A', '#FFAE6B', '#7FF9E3', '#D883FF', '#AB6E3B'])


def parser(x):
    return datetime.strptime('202'+x, '%Y-%m-%d')


gl0bal = read_csv('https://raw.githubusercontent.com/ll-cooool-j/DS-Assignment/main/Datasets/Separated%20datasets%20(for%20custom%20visuals)/stringency%20index.csv',header=0, parse_dates=[0], index_col=0, squeeze=True, date_parser=parser)

fig, ax = plt.subplots(figsize=(12,8))
ax.plot(gl0bal['Brazil'], label="Brazil")
ax.plot(gl0bal['US'], label="US")
ax.plot(gl0bal['India'], label="India")
ax.plot(gl0bal['Japan'], label="Japan")
ax.plot(gl0bal['Korea'], label="Korea")
ax.plot(gl0bal['Vietnam'], label="Vietnam")
ax.legend()
ax.set_title('Stringency Index of all countries')
plt.show()