%Get Data, and Predict, for Multiple Areas
% Retrieves data from public sources, and estimates an "SIR" model 
% using these data, for multiple areas. The estimated parameters for the
% SIR model are plotted using data that changes as additional information
% is gained over time.
%
% Relies upon: 
% * RetrieveAndAnaliseCV19Data
% * fitVirusCV19 command. 
%   This command can be run immediately afterwards to illustrate the projected
%   path of the epidemic, using the parameters that are estimated using the 
%   full data set presented to this function. Note the parameters shown in
%   the figure generated by this function for R_0 (top panel), Population (bottom panel),
%   and C_end (middle panel) are used in the projection generated using this
%   command, and are shown in the graph it generates.
% 
% This is an illustration using a mathematical model. It is not health advice.
% See important limitations below. 
%
% Sources:
% 1. Patrick Anderson, using "fitVirusCV19" utility from source 2.
% 2. Milan Batista (2020). fitVirusCOVID19
%   (https://www.mathworks.com/matlabcentral/fileexchange/74658-fitviruscovid19),
%   MATLAB Central File Exchange. Retrieved March 29, 2020. 
% 3. The retrieval utilities collect data from multiple public sources, which may
%   or may not be reliable, and which have not been reviewed by the author of
%   this utility. These source data are not from the authors listed in [1] and [2].
%   The data sources for many countries are described and maintained here:
%   <https://ourworldindata.org/coronavirus-source-data.>
%   <https://www.worldometers.info/coronavirus/coronavirus-cases>
%   Note there are discrepancies between these data and the data maintained by
%   authorities within various countries. For example, as of March 29, 2020, the US CDC data is not
%   identical to that published by other sources. This may be due to differences
%   in counting persons repatriated from China:
%   <https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/cases-in-us.html>.
%
% No copyright or license claimed on code retrieved from file exchange
% cited above, other than what is claimed in "license.txt." No warranty is
% provided as stated in the license.txt file.
%
% *Limitations*
% 
% 1. This routine relies upon publicly-available data sources that are not reviewed
%    by the authors of this routine, and may be subject to reporting errors, 
%    limitations in testing, censorship or pressure, and changes in testing protocols.
%    Therefore, do not rely upon data or visualizations produced or retrieved by this utility,
%    other than as an illustration. The user is solely responsible for confirming
%    the data and interpreting the results. 
% 2. The "SIR" model, while widely used and extremely useful, has certain
%    limitations. Furthermore, all models rely upon parameters, and functional forms, 
%    that are imperfect at best.
% 3. This is not health advice, nor legal advice.
% 4. There is no warranty on this utility. 

%% Get Data; Analise; Visualize

clc
close all
line = '--------------------------------------';

disp(' Starting retrieval and illustration of data.');
   disp(' '); disp(line); disp(' ');

disp(' Italy ');
disp(' ');

getdatafunction = @getDataItaly;
   n = 10;

%   Italy, data set from 10 days till current set
   [OutItaly, H1] = RetrieveAndAnaliseCV19Data(getdatafunction, n);
   disp(OutItaly);
   disp(' ');
   
   aut1 = fitVirusCV19(getdatafunction,'prn','on','nmax',1e5);
   H2 = gcf;
   H2.Name = "Projection, SIR Model, Data for: " + OutItaly.Area;

   disp(' '); disp(line); disp(' ');
   
   
%   Lombardia Province of Italy, data set from 10 days till current set 
disp(' Lombardia ');
disp(' ');
getdatafunction = @getDataLombardia;

   n = 10;
   [OutLombard, H11] = RetrieveAndAnaliseCV19Data(getdatafunction, n);
   disp(OutLombard);
   disp(' ');

   aut2 = fitVirusCV19(getdatafunction,'prn','on','nmax',1e5);
   H12 = gcf;
   H12.Name = "Projection, SIR Model, Data for: " + OutLombard.Area;
   
   disp(' '); disp(line); disp(' ');   
   
   
%   USA, StartDay = 15
disp(' USA ');
disp(' ');
getdatafunction = @getDataUSA;

    n = 15;
    [OutUSA, H3] = RetrieveAndAnaliseCV19Data(getdatafunction, n);
    disp(OutUSA);

    fitVirusCV19(getdatafunction ,'prn','on','nmax',10e5);
    H4 = gcf;
    H4.Name = "Projection, SIR Model, Data for: " + OutUSA.Area;

    disp(' '); disp(line); disp(' ');
    
% Germany, StartDay = 20    
disp(' Germany ');
disp(' ');
getdatafunction = @getDataGermany;

    n = 20;
    [OutGermany, H5] = RetrieveAndAnaliseCV19Data(getdatafunction,n);
    disp(OutGermany);

    fitVirusCV19(getdatafunction,'prn','on','nmax',5e5);
    H6 = gcf;
    H6.Name = "Projection, SIR Model, Data for: " + OutGermany.Area;
    

    

